gemfile: kubernetes/Gemfile
rvm:
  - 2.7
  - 3.2

before_install:
  - gem update --system
  - gem install bundler

script:
- cd kubernetes
- bundle exec rubocop ./src
- bundle exec rubocop ./spec
- bundle exec rspec
