# frozen_string_literal: true

# #Kubernetes
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: v1.13.4
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
# Swagger Codegen version: 2.2.3
#

require 'date'

module Kubernetes
  # PodDisruptionBudgetStatus represents information about the status of a PodDisruptionBudget. Status may trail the actual state of a system.
  class V1beta1PodDisruptionBudgetStatus
    # current number of healthy pods
    attr_accessor :current_healthy

    # minimum desired number of healthy pods
    attr_accessor :desired_healthy

    # DisruptedPods contains information about pods whose eviction was processed by the API server eviction subresource handler but has not yet been observed by the PodDisruptionBudget controller. A pod will be in this map from the time when the API server processed the eviction request to the time when the pod is seen by PDB controller as having been marked for deletion (or after a timeout). The key in the map is the name of the pod and the value is the time when the API server processed the eviction request. If the deletion didn't occur and a pod is still there it will be removed from the list automatically by PodDisruptionBudget controller after some time. If everything goes smooth this map should be empty for the most of the time. Large number of entries in the map may indicate problems with pod deletions.
    attr_accessor :disrupted_pods

    # Number of pod disruptions that are currently allowed.
    attr_accessor :disruptions_allowed

    # total number of pods counted by this disruption budget
    attr_accessor :expected_pods

    # Most recent generation observed when updating this PDB status. PodDisruptionsAllowed and other status informatio is valid only if observedGeneration equals to PDB's object generation.
    attr_accessor :observed_generation

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        current_healthy: :currentHealthy,
        desired_healthy: :desiredHealthy,
        disrupted_pods: :disruptedPods,
        disruptions_allowed: :disruptionsAllowed,
        expected_pods: :expectedPods,
        observed_generation: :observedGeneration
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        current_healthy: :Integer,
        desired_healthy: :Integer,
        disrupted_pods: :'Hash<String, DateTime>',
        disruptions_allowed: :Integer,
        expected_pods: :Integer,
        observed_generation: :Integer
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.transform_keys(&:to_sym)

      self.current_healthy = attributes[:currentHealthy] if attributes.key?(:currentHealthy)

      self.desired_healthy = attributes[:desiredHealthy] if attributes.key?(:desiredHealthy)

      if attributes.key?(:disruptedPods) && (value = attributes[:disruptedPods]).is_a?(Array)
        self.disrupted_pods = value
      end

      if attributes.key?(:disruptionsAllowed)
        self.disruptions_allowed = attributes[:disruptionsAllowed]
      end

      self.expected_pods = attributes[:expectedPods] if attributes.key?(:expectedPods)

      return unless attributes.key?(:observedGeneration)

      self.observed_generation = attributes[:observedGeneration]
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = []
      if @current_healthy.nil?
        invalid_properties.push("invalid value for 'current_healthy', current_healthy cannot be nil.")
      end

      if @desired_healthy.nil?
        invalid_properties.push("invalid value for 'desired_healthy', desired_healthy cannot be nil.")
      end

      if @disruptions_allowed.nil?
        invalid_properties.push("invalid value for 'disruptions_allowed', disruptions_allowed cannot be nil.")
      end

      if @expected_pods.nil?
        invalid_properties.push("invalid value for 'expected_pods', expected_pods cannot be nil.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @current_healthy.nil?
      return false if @desired_healthy.nil?
      return false if @disruptions_allowed.nil?
      return false if @expected_pods.nil?

      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(other)
      return true if equal?(other)

      self.class == other.class &&
        current_healthy == other.current_healthy &&
        desired_healthy == other.desired_healthy &&
        disrupted_pods == other.disrupted_pods &&
        disruptions_allowed == other.disruptions_allowed &&
        expected_pods == other.expected_pods &&
        observed_generation == other.observed_generation
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(other)
      self == other
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [current_healthy, desired_healthy, disrupted_pods, disruptions_allowed, expected_pods,
       observed_generation].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)

      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            send("#{key}=", attributes[self.class.attribute_map[key]].map do |v|
                              _deserialize(Regexp.last_match(1), v)
                            end)
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = Kubernetes.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = send(attr)
        next if value.nil?

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
