# frozen_string_literal: true

# #Kubernetes
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: v1.13.4
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
# Swagger Codegen version: 2.2.3
#

require 'date'

module Kubernetes
  # ReplicaSetStatus represents the current status of a ReplicaSet.
  class V1beta1ReplicaSetStatus
    # The number of available replicas (ready for at least minReadySeconds) for this replica set.
    attr_accessor :available_replicas

    # Represents the latest available observations of a replica set's current state.
    attr_accessor :conditions

    # The number of pods that have labels matching the labels of the pod template of the replicaset.
    attr_accessor :fully_labeled_replicas

    # ObservedGeneration reflects the generation of the most recently observed ReplicaSet.
    attr_accessor :observed_generation

    # The number of ready replicas for this replica set.
    attr_accessor :ready_replicas

    # Replicas is the most recently oberved number of replicas. More info: https://kubernetes.io/docs/concepts/workloads/controllers/replicationcontroller/#what-is-a-replicationcontroller
    attr_accessor :replicas

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        available_replicas: :availableReplicas,
        conditions: :conditions,
        fully_labeled_replicas: :fullyLabeledReplicas,
        observed_generation: :observedGeneration,
        ready_replicas: :readyReplicas,
        replicas: :replicas
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        available_replicas: :Integer,
        conditions: :'Array<V1beta1ReplicaSetCondition>',
        fully_labeled_replicas: :Integer,
        observed_generation: :Integer,
        ready_replicas: :Integer,
        replicas: :Integer
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.transform_keys(&:to_sym)

      if attributes.key?(:availableReplicas)
        self.available_replicas = attributes[:availableReplicas]
      end

      if attributes.key?(:conditions) && (value = attributes[:conditions]).is_a?(Array)
        self.conditions = value
      end

      if attributes.key?(:fullyLabeledReplicas)
        self.fully_labeled_replicas = attributes[:fullyLabeledReplicas]
      end

      if attributes.key?(:observedGeneration)
        self.observed_generation = attributes[:observedGeneration]
      end

      self.ready_replicas = attributes[:readyReplicas] if attributes.key?(:readyReplicas)

      self.replicas = attributes[:replicas] if attributes.key?(:replicas)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = []
      if @replicas.nil?
        invalid_properties.push("invalid value for 'replicas', replicas cannot be nil.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @replicas.nil?

      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(other)
      return true if equal?(other)

      self.class == other.class &&
        available_replicas == other.available_replicas &&
        conditions == other.conditions &&
        fully_labeled_replicas == other.fully_labeled_replicas &&
        observed_generation == other.observed_generation &&
        ready_replicas == other.ready_replicas &&
        replicas == other.replicas
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(other)
      self == other
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [available_replicas, conditions, fully_labeled_replicas, observed_generation, ready_replicas,
       replicas].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)

      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            send("#{key}=", attributes[self.class.attribute_map[key]].map do |v|
                              _deserialize(Regexp.last_match(1), v)
                            end)
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = Kubernetes.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = send(attr)
        next if value.nil?

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
