# frozen_string_literal: true

#
# #Kubernetes
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: v1.13.4
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
# Swagger Codegen version: 2.2.3
#

$LOAD_PATH.push File.expand_path('lib', __dir__)
require 'kubernetes/version'

Gem::Specification.new do |s|
  s.name        = 'kubernetes-io'
  s.version     = Kubernetes::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ['Kubernetes authors']
  s.email       = ['jeroen@clearcodewizards.com']
  s.homepage    = 'https://github.com/clearcodewizards/kubernetes-io'
  s.summary     = 'Kubernetes ruby client.'
  s.description = 'Kubernetes official ruby client to talk to kubernetes clusters. ' \
                  'Fork from https://github.com/kubernetes-client/ruby with Ruby version 3 support.'
  s.license     = 'Apache-2.0'
  s.required_ruby_version = '>= 2.7'

  s.add_runtime_dependency 'json', '~> 2.1', '>= 2.1.0'
  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'autotest', '~> 4.4', '>= 4.4.6'
  s.add_development_dependency 'autotest-fsevent', '~> 0.2', '>= 0.2.12'
  s.add_development_dependency 'autotest-growl', '~> 0.2', '>= 0.2.16'
  s.add_development_dependency 'autotest-rails-pure', '~> 4.1', '>= 4.1.2'
  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'
  s.add_development_dependency 'vcr', '~> 3.0', '>= 3.0.1'
  s.add_development_dependency 'webmock', '~> 1.24', '>= 1.24.3'

  s.files         = `find *`.split("\n").uniq.sort.reject(&:empty?)
  s.executables   = []
  s.require_paths = %w[lib src]
  s.metadata['rubygems_mfa_required'] = 'true'
end
